name: Docker Merge

on:
  pull_request:
    types: [closed]
    paths:
      - people/**

jobs:
  post_merge:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        run: docker run ghcr.io/nmagee/ds2002-directory:v3
